### ISSUE TITLE
Not able to get response from get_messages

### ISSUE THREAD

**Issue by Manny91** [levz0r/gmail-tester#1]
Hi,

I am starting with gmail-tester and so far I've managed to get the token when authenticating the app and allowing access to it but now the issue I'm facing is get-messages task not returning anything:

here's the example code I grabbed from the example:

task  
```
const debug = require("debug");
const path = require("path");
const gmail_tester = require("../../node_modules/gmail-tester");

module.exports = (on, config) => {
  on("task", {
    "gmail:get-messages": async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve("../", "credentials.json"),
        path.resolve("../", "token.json"),
        args.options
      );
      return messages;
    }
  });
};
```
and then in my test

```
describe("Email assertion:", () => {
  it("Look for an email with specific subject and link in email body", function() {
    // debugger; //Uncomment for debugger to work...
         cy.task("gmail:get-messages", {
      options: {
        include_body: true
      }
    }).then(emails => {
      // debugger;
      console.log('emails', emails);
      assert.isTrue(emails, "tesstss");
    });

  });
});
```

but the error I can see is 

```
CypressError: cy.task('gmail:get-messages') failed with the following error:

The task 'gmail:get-messages' returned undefined. You must return a promise, a value, or null to indicate that the task was handled.

The task handler was:

async args => {
      const messages = await gmail_tester.get_messages(
        path.resolve("../", "credentials.json"),
        path.resolve("../", "token.json"),
        args.options
      );
      return messages;
    }

```

If I try to use the gmail.check_inbox method I have timeouts 😕

**Comment by levz0r** [comment]
Sorry to hear your'e having issues... 
Can you provide a repo with reproduction?

**Comment by Manny91** [comment]
Hi @levz0r, 

Thanks for your response,

I've create just a quick create-react app project : https://github.com/Manny91/cypress-gmail-test need to go inside the main folder and do `npm i` and then in order to run the test suite just run `npm run cypress:open`

I've sent an email to myself so test I guess should pass, but now doing gmail:check can't find it

**Comment by levz0r** [comment]
Are you still getting `The task 'gmail:get-messages' returned undefined.` error?

**Comment by Manny91** [comment]
I am getting in console
when trying to get all the messages

```Error: TypeError: Cannot read property 'value' of undefined
    at _get_recent_email (/Users/*/cypress-gmail-test/cypress-gmail-test/node_modules/gmail-tester/gmail-tester.js:19:9)```

**Comment by levz0r** [comment]
Try to uncomment `debugger;` on line 11 in `cypress\integration\gmail.spec.js`, then open the spec file in cypress runner with Developer Tools open (F12). You should be able to see all unread emails in your inbox. 
![image](https://user-images.githubusercontent.com/4564386/57799505-ee934600-7757-11e9-80f7-99f60655627c.png)

**Comment by levz0r** [comment]
I am closing this issue. Feel free to reopen if you still experience problems.

**Comment by kdepp** [comment]
Please reopen this ticket ,  I can reproduce this bug with a recently registered gmail account.

There are chances `Delivered-To` is not present in head

```
[{
    name: 'MIME-Version',
    value: '1.0'
}, {
    name: 'x-no-auto-attachment',
    value: '1'
}, {
    name: 'Received',
    value: 'by 2002:ac9:6084:0:0:0:0:0; Fri, 7 Jun 2019 19:19:47 -0700 (PDT)'
}, {
    name: 'Date',
    value: 'Fri, 7 Jun 2019 19:19:47 -0700'
}, {
    name: 'Message-ID',
    value: '<CANLmZMWPsu=3bEwO3qGzVZRWVrSPrJzqxW8Pd9n7We3WkLzswg@mail.gmail.com>'
}, {
    name: 'Subject',
    value: 'Tips for using your new inbox'
}, {
    name: 'From',
    value: 'Gmail Team <mail-noreply@google.com>'
}, {
    name: 'To',
    value: 'XXX Name <xxx@gmail.com>'
}, {
    name: 'Content-Type',
    value: 'multipart/alternative; boundary="000000000000c1768e058ac6943b"'
}]
```

**Comment by Manny91** [comment]
I ended up forking it and did some fixes and added few stuff about because I needed some additional funcionality:
-  improving the matching of the emails,
-  functionality to filter the query of emails by label
- update the labels of an email

**Comment by levz0r** [comment]
@Manny91 Can you please check with @kdepp's [PR](https://github.com/levz0r/gmail-tester/pull/2)?

**Comment by VaghasiyaKrupal** [comment]
I am facing the same issue in `cypress 10.1.0`, but it's worked in an older version of cypress. now below error, I'm receiving. Does anyone have any solution?
```
cy.task('gmail:get-messages') failed with the following error:

The task 'gmail:get-messages' returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled.

The task handler was:

async args => {
          const messages = await gmail_tester.get_messages(
            path.resolve(__dirname, "credentials.json"),
            path.resolve(__dirname, "token.json"),
            args.options
          );
          console.log(messages);
          return messages;
        }

Fix this in your setupNodeEvents method here:
/home/krupal/Desktop/Cypress Automation/RebelBase/cypress.config.js
```
