### ISSUE TITLE
Bug: date query formatting 1 month out

### ISSUE THREAD

**Issue by majicmoo** [levz0r/gmail-tester#10]
Hey :)

Thanks for making this, made my life a lot easier when trying to add gmail tests 👍 

I've found a small bug around date formatting. In the `_init_query` getMonth is called. This is zero indexed so the date comes out wrong, e.g Januray 1st 1999 would be 1999/0/1.
https://github.com/levz0r/gmail-tester/blob/master/gmail-tester.js#L15

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth

**Comment by levz0r** [comment]
Thank you for reporting, @majicmoo. 

Actually `Date()` object is zero-index based. Therefor, as shown in https://github.com/levz0r/gmail-tester/blob/master/README.md, To find messages received in January, you should initialize the following `options` object:
```
{
   before: new Date(2019, 1, 1),
   after: new Date(2019, 0, 1)
}
```
