### ISSUE TITLE
check_inbox - Cannot destructure property 'HTTP2_HEADER_CONTENT_ENCODING' of 'http2.constants' as it is undefined. e

### ISSUE THREAD

**Issue by chaozek** [levz0r/gmail-tester#129]
Hello,
Iam getting following error:

![image](https://user-images.githubusercontent.com/66912514/218123389-a80f01e4-3314-4600-8a82-4493bc43f700.png)

`  > Cannot destructure property 'HTTP2_HEADER_CONTENT_ENCODING' of 'http2.constants' as it is undefined.`

```
`  23 | const process = require("process");
  24 | const common_1 = require("gaxios/build/src/common");
> 25 | const { HTTP2_HEADER_CONTENT_ENCODING, HTTP2_HEADER_CONTENT_TYPE, HTTP2_HEADER_METHOD, HTTP2_HEADER_PATH, HTTP2_HEADER_STATUS, } = http2.constants;
     |        ^
  26 | const DEBUG = !!process.env.HTTP2_DEBUG;
  27 | /**
  28 |  * List of sessions current in use.
```

code:

```
 it.only('07_A_FORMS- Verify if form "SIGN IN NEWSLETTER" is redirected on correct page', () => {
    cy.task("gmail:check", {
      from: "no-reply@domain.com",
      to: "FA",
      subject: "Confirm your account",
    }).then((email) => {
      assert.isNotNull(email, `Email was not found`);
    });
  });
```
I've tried latest [1.3.8](https://www.npmjs.com/package/gmail-tester/v/1.3.8)  & previous [1.3.5](https://www.npmjs.com/package/gmail-tester/v/1.3.5). No success.

Also node_modules reinstall didn't do anything.

If iIam running `get_messages()` api, everything's good. 
Any ideas?
Running on `node 19.4.0 (Currently using 64-bit executable)`
Thank you!

**Comment by chaozek** [comment]
SOLVED: Problem was I've never visited my site so you have to cy.visit("/some-url") first

**Comment by levz0r** [comment]
Glad you solved it :)
