### ISSUE TITLE
Error [gmail] Error: TypeError: gmail_emails is not iterable when checking email

### ISSUE THREAD

**Issue by rifer** [levz0r/gmail-tester#14]
Hi, first of all, thanks for your plugin, it's being very useful.

I wonder if you could provide me with some advice or support on this topic I've seen in other issues as closed. Find attached a screenshot with the console output I am getting when checking for an email I positively now has reach the inbox:

![bug](https://user-images.githubusercontent.com/13977524/68995262-f4dfb780-088b-11ea-8846-ec4b3eb88e16.png)

If there is anything else I can add to understand the issue just say it and I'll do my best.

Thanks in advance!

**Comment by levz0r** [comment]
Hi @rifer,

What is the version of gmail-tester you are using?

**Comment by rifer** [comment]
Hi @levz0r , thanks for your quick response

It's declared like this in my package.json: 
`"gmail-tester": "^1.1.4"`

**Comment by levz0r** [comment]
Can you update to 1.1.5?

**Comment by marinakuranda** [comment]
Writing here to confirm that I had a similar issue and updating to 1.1.5 has solved it.
Thank you for creating this plugin!

**Comment by rifer** [comment]
My apologies for not updating this issue.
Also worked on my end, so I will close it.

Thanks!!

**Comment by igor-resende-ifood** [comment]
Hi @rifer I was having a similar issue with the version `^1.1.4`, but updating to the `1.1.5` did not solve it.. 
It only happens occasionally, =/
![Captura de Tela 2020-02-06 às 09 30 29](https://user-images.githubusercontent.com/54079184/73937443-cccc8700-48c3-11ea-8c2a-cd90347aa4e9.png)

**Comment by levz0r** [comment]
@igor-resende-ifood, today I've merged https://github.com/levz0r/gmail-tester/pull/21 which should rethrow the actual error in such case. Please update the library to the latest version.
