### ISSUE TITLE
check_inbox allows passing duplicated options

### ISSUE THREAD

**Issue by marinakuranda** [levz0r/gmail-tester#15]
Hi Lev!

Thank you for creating this library! :+1: 
I wanted to leave some feedback regarding `check_inbox`.

There's an opportunity for passing `from, to, subject` as arguments and as a part of `options`, which is a bit confusing. This creates a situation where it is possible to poll for emails with one filter, while the actual messages received from the API are filtered using different options.

Maybe it would make sense to stick to the options and remove the extra arguments?

**Comment by levz0r** [comment]
Hi @marinakuranda, thanks for addressing this. 

You're definitely right. Would you want to make a contribution by fixing this? If not, it's ok, I'll take a look in a couple of days (a bit busy). BTW, When fixing, we need to make sure it is backward compatible.

**Comment by marinakuranda** [comment]
Thanks for your reply!

I'm up for fixing this, but I can't think of a way to do it in a backward-compatible fashion.

From my point of view `subject, from, to` should be specified in one place, so we would either need to:

1. remove those arguments from `check_inbox` and pass everything using `options`
2. ignore properties with the same names inside `options` and use the argument values

I like the second option because it makes the requirements explicit.
I think both options would introduce a breaking change.

Do you have another idea on your mind?
