### ISSUE TITLE
Can't start server

### ISSUE THREAD

**Issue by hieutrandn9889** [levz0r/gmail-tester#16]
Hello,

I apply gmail-tester for my example but I got an issue about start server

I run OS; Mac: 10.15.2 and chrome: 79 and cypress: 3.8.0
**My log:**
 Can't start server

Cypress failed to make a connection to the Chrome DevTools Protocol after retrying for 20 seconds.

This usually indicates there was a problem opening the Chrome browser.

The CDP port requested was 53784.

Error details:

Error: connect ECONNREFUSED 127.0.0.1:53784 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)

=====================
Failed to connect to Chrome, retrying in 1 second (attempt 18/32)
Failed to connect to Chrome, retrying in 1 second (attempt 19/32)
Failed to connect to Chrome, retrying in 1 second (attempt 20/32)
Failed to connect to Chrome, retrying in 1 second (attempt 21/32)
HEAD / - - ms - -
HEAD / - - ms - -
HEAD / - - ms - -
Failed to connect to Chrome, retrying in 1 second (attempt 22/32)
Failed to connect to Chrome, retrying in 1 second (attempt 23/32)
Failed to connect to Chrome, retrying in 1 second (attempt 24/32)
Failed to connect to Chrome, retrying in 1 second (attempt 25/32)
Failed to connect to Chrome, retrying in 1 second (attempt 26/32)
Failed to connect to Chrome, retrying in 1 second (attempt 27/32)
Failed to connect to Chrome, retrying in 1 second (attempt 28/32)
Failed to connect to Chrome, retrying in 1 second (attempt 29/32)
Failed to connect to Chrome, retrying in 1 second (attempt 30/32)
Failed to connect to Chrome, retrying in 1 second (attempt 31/32)
Failed to connect to Chrome, retrying in 1 second (attempt 32/32)

**Comment by levz0r** [comment]
Hi,
gmail-tester is not related in any way to cypress. 
Please open an issue on cypress github, or follow https://github.com/cypress-io/cypress/issues/5912

Thanks
