### ISSUE TITLE
[gmail] Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined

### ISSUE THREAD

**Issue by andreabisello** [levz0r/gmail-tester#19]
this is my code

```

        const email = await gmail.check_inbox(
            path.resolve(__dirname, "gmail-credentials.json"), // Assuming credentials.json is in the current directory.
            path.resolve(__dirname, "gmail-token.json"), // Look for gmail_token.json in the current directory (if it doesn't exists, it will be created by the script).
            "alert", // We are looking for 'Activate Your Account' in the subject of the message.
            "google", // We are looking for a sender header which has 'no-reply@domain.com' in it.
            "xxx@gmail.com", // Which inbox to poll. credentials.json should contain the credentials to it.
            10, // Poll interval (in seconds).
            30, // Maximum poll time (in seconds), after which we'll giveup.
            {include_body: true} // If we want to include the body of messages (optional)
            )
        ;

        if(email){
            console.log(email)
        }

```

gmail-credentials.json and gmail-token.json are in the same directory,

and this works

![image](https://user-images.githubusercontent.com/2149815/71658397-2f21ed00-2d44-11ea-869b-41107a400248.png)

but in node, this is the output

```
console.log node_modules/gmail-tester/gmail-tester.js:108
    [gmail] Checking for message from 'google', to: xxxxxxxx@gmail.com, contains 'alert' in subject...

  console.log node_modules/gmail-tester/gmail-tester.js:145
    [gmail] Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
        at Function.from (buffer.js:293:9)
        at _get_recent_email (C:\src\e2e\node_modules\gmail-tester\gmail-tester.js:84:36)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at Object.check_inbox (C:\src\e2e\node_modules\gmail-tester\gmail-tester.js:115:22)
        at Object.<anonymous> (C:\src\e2e\test\gmailTest.test.js:8:23) {
      code: 'ERR_INVALID_ARG_TYPE'
    }
```
any suggestion please?
thanks

**Comment by levz0r** [comment]
Hello,
Can you please upgrade to the latest version and try again? Please notice that there was a breaking change in `check_inbox` method, so you need to pass the email-related parameters using the `options` object.

**Comment by andreabisello** [comment]
@levz0r  now it works!
thanks!

so i have to use 

check_inbox

if i want to check agains the existence of a mail,

instead i need to use

get_messages

to obtain all the message, right?

**Comment by levz0r** [comment]
> @levz0r now it works!
> thanks!
> 
> so i have to use
> 
> check_inbox
> 
> if i want to check agains the existence of a mail,
> 
> instead i need to use
> 
> get_messages
> 
> to obtain all the message, right?

Glad to hear!

Both functions use the same underlying logic. The difference is that `check_inbox` returns a true/false value depends if the email is found, while `get_messages` essentially returns the emails. For further information, please refer to https://github.com/levz0r/gmail-tester/blob/master/README.md.
