### ISSUE TITLE
instructions unclear when creating credentials

### ISSUE THREAD

**Issue by elliottjro** [levz0r/gmail-tester#22]
Was running into issues when trying to create a token because I selected "web-application" when creating 0Auth creds. 

Threw error when trying to run `init.js`
```
[gmail] Error: TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.
    at Object.authorize
```

## FIX: 
`credentials.json` MUST be in the format (generate OAuth as `Other` type
```
{
  "installed": {
     ...
  }
}
```

**Comment by levz0r** [comment]
Hi @elliottjro,

The README was updated. Thank you for suggesting.
