### ISSUE TITLE
Issue: run init.js command in terminal doesn't work?

### ISSUE THREAD

**Issue by AlexanderKYH** [levz0r/gmail-tester#26]
Every time I try to run node ..\..\node_modules\gmail-tester\init.js .\credentials.json gmail_token.json my_emailaddress@gmail.com in terminal, I get an Error message "This functionality is absolete! Please pass all params in options object!". Does any one know whats the problem?
Maybe Google made some changes with the API?

**Comment by levz0r** [comment]
Please update to latest version (published a few minutes ago).
