### ISSUE TITLE
Always have to provide to, from and subject when checking for mail

### ISSUE THREAD

**Issue by webnexusmobile** [levz0r/gmail-tester#29]
Hi, 

thanks for the great work, this module came in very handy!

When trying it out, I was wondering, why this part in the __check_inbox function might be necessary because the emails that you loop over here have already been filtered according to "to", "subject" and "from" in _get_recent_email (this loop won't find anything if we didin't provide all three filters):

```javascript
     for (let email of emails) {
        if (
          email.receiver === to &&
          email.subject.indexOf(subject) >= 0 &&
          email.from.indexOf(from) >= 0
        ) {
          console.log(`[gmail] Found!`);
          found_email = email;
          break;
        }
      }
```

This additional filtering has the effect, that we cannot check for combinations of e.g. just "to" and "from" because this loop always checks against all three of them. I was able to make this work by replacing the for loop with just this:

```javascript
if(emails) {
  console.log(`[gmail] Found!`);
  found_email = emails[0];
}
```
Is there any good reason for the loop that I did not see?

Regards.

**Comment by levz0r** [comment]
Hi @webnexusmobile,

Thank you for opening this issue.

Looks like this code can be removed indeed. It is there because at the beginning I wasn't using the querying mechanism for looking for emails, and the filtering was performed by the code.

Would you like to create a PR for this?

Thanks
