### ISSUE TITLE
Uses a vunuerable version of googleapis

### ISSUE THREAD

**Issue by aidanlane** [levz0r/gmail-tester#3]
From https://www.npmjs.com/advisories/791

### Overview
Versions of googleapis prior to 38.0.0 are vulnerable to Improper Authorization. Setting credentials to one client may apply to all clients which may cause requests to be sent with the incorrect credentials.

### Remediation
Upgrade to version 38.0.0.

### Resources
(GitHub Issue)[https://github.com/googleapis/google-api-nodejs-client/issues/1594]

**Comment by aidanlane** [comment]
Wow, that was a super quick response- MIND. BLOWN! Thank you!!

**Comment by levz0r** [comment]
Thanks for reporting @aidanlane!
