### ISSUE TITLE
Can't get check-inbox to work.

### ISSUE THREAD

**Issue by Jacek-fstack** [levz0r/gmail-tester#31]
Hi, here's my issue
I have an app in which you fill out the form and the email arrives after 10-15 seconds with confirmation.

I tried get-messages, and since it can't wait for email I used hard-coded wait, and it was finding the mail just fine, as well as doing assertions.

So I tried adding check-message before that, and it seems like it never waits for the message. It's just... there.
So the test goes through and fails on the get-messages, because the email didn't arrive yet.

I'm guessing the check-message fails, because I am providing only "TO" parameter (and trying assertion on the body, since I think we can do that). The FROM and Subject are every time a bit different, and I tried adding regexp, which won't work 
from: "noreply.*", 
to: myEmail,
subject: FormName.*;

Long story short - if I don't do assertion, it just finishes the wait in 5 seconds, instead of waiting the 30. If I do assertion it fails on `function(){} TypeError: Cannot read property 'length' of null
`
```
cy.task("gmail:check-inbox", {
            options: {
                to: emailAnswer
            }
        }).then(emails => {
            assert.isAtLeast(
                emails.length,
                1,
                "Expected to find at least one email, but none were found!"
            );
            const body = emails[0].body.html;
            assert.isTrue(
                body.indexOf(
                    emailAnswer
                ) >= 0,
                "Found Email field answer!"
            );
            assert.isTrue(
                body.indexOf(
                    shortAnswer
                ) >= 0,
                "Found short answer field answer!"
            );
        });
```

**Comment by anas-qa** [comment]
Check the example on readme => https://github.com/levz0r/gmail-tester#example

No need for the hard-coded wait, you can define in your plugins/index.js

<img width="752" alt="Screen Shot 2020-03-09 at 6 12 22 PM" src="https://user-images.githubusercontent.com/16471809/76220842-991dad80-6231-11ea-8777-5bd8f48a4145.png">

**Comment by Jacek-fstack** [comment]
Well it's not working at all, that's my point ; ) It just ignores the wait times.

**Comment by Jacek-fstack** [comment]
Update: Managed to get it to work, it was my mistake, I was using options{} instead of directly giving the parameters.. Unfortunately, I still can't search by a partial email subject. Is that an option? regexp or *s don't seem to be working.

**Comment by levz0r** [comment]
Hi @Jacek-fstack,

Sorry for the late reply. I am glad you've managed to solve the issue.

Regarding the search: the subject is exact. If you're unsure what is the subject, you can simply omit the parameter and it will search mails using the other provided filters.
