### ISSUE TITLE
Is it any way to poll 'Sent' messages

### ISSUE THREAD

**Issue by sergtimosh** [levz0r/gmail-tester#32]
Hi! Thanks for your great library. I managed to add it to my puppeteer tests, and it works just fine :)
And now new test problem raised.
I need to verify, that smtp is configured correctly in the tested application and messages are sent within gmail account.
Is it any way I can use gmail-tester for polling 'Sent' gmail box?
Thanks in advance!

**Comment by levz0r** [comment]
Hi @sergtimosh,

Sorry for the late reply, crazy times...

Well, there is a way: Change INBOX to SENT here:
https://github.com/levz0r/gmail-tester/blob/1e82c5aa2741012cc3cc2dffc13382a617aaa735/gmail.js#L164, change from
