### ISSUE TITLE
check-inbox not returning an array

### ISSUE THREAD

**Issue by bkosse** [levz0r/gmail-tester#33]
According to the documentation on check-inbox, it should return an array of email objects. When running the task, I only get the most recent email returned as an object.

plugins/index.js

```js
on("task", 
{
    "gmail:check-inbox": async args => {
      const email = await gmail_tester.check_inbox(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json"),
        args.options
      );
      return email;
    }
  });
```

testcase.js:
```js
cy.task("gmail:check-inbox", {
            options: {
                from: emailfrom,
                subject: emailsubject,
                wait_time_sec: 10, // Poll interval (in seconds).
                max_wait_time_sec: 30, // Maximum poll time (in seconds), after which we'll giveup.
                include_body: true
            }
        }).then(emails => {
            cy.log(emails)
        });
```

**Comment by bkosse** [comment]
Also, I'm not sure if I'm using check-inbox correct. It took me a while to translate the example on check-inbox into a working script.

When using check-inbox, Cypress already reports successful while gmail-tester is still polling for the email. Is that correct?

**Comment by sergeyblohin** [comment]
@bkosse I also faced this problem.
I believe that the error crept into the documentation.
The source code clearly States that the first email found will be returned.
You can change the source code, or live with a single email.

see the 116 line of gmail-tester.js file:
https://github.com/levz0r/gmail-tester/blob/1e82c5aa2741012cc3cc2dffc13382a617aaa735/gmail-tester.js#L116

**Comment by levz0r** [comment]
> According to the documentation on check-inbox, it should return an array of email objects. When running the task, I only get the most recent email returned as an object.
> 
> plugins/index.js
> 
> ```js
> on("task", 
> {
>     "gmail:check-inbox": async args => {
>       const email = await gmail_tester.check_inbox(
>         path.resolve(__dirname, "credentials.json"),
>         path.resolve(__dirname, "token.json"),
>         args.options
>       );
>       return email;
>     }
>   });
> ```
> 
> testcase.js:
> 
> ```js
> cy.task("gmail:check-inbox", {
>             options: {
>                 from: emailfrom,
>                 subject: emailsubject,
>                 wait_time_sec: 10, // Poll interval (in seconds).
>                 max_wait_time_sec: 30, // Maximum poll time (in seconds), after which we'll giveup.
>                 include_body: true
>             }
>         }).then(emails => {
>             cy.log(emails)
>         });
> ```

Hello,
Well, there is indeed a confusion regarding this in the documentation. On one hand, it says:
> check_inbox(): Polls a mailbox for a given amount of time. At the end of the operation, the desired **message** is returned (if found).

on the other:

> Returns: An array of **email objects** with the following fields: ...

Personally I'm usually searching for specific messages and therefor expecting check_inbox() to return a single object. 

Is your use case different?

**Comment by levz0r** [comment]
> Also, I'm not sure if I'm using check-inbox correct. It took me a while to translate the example on check-inbox into a working script.
> 
> When using check-inbox, Cypress already reports successful while gmail-tester is still polling for the email. Is that correct?

Please check usage example in [gmail.spec.js](https://github.com/levz0r/gmail-tester/blob/master/examples/cypress/integration/gmail.spec.js)
