### ISSUE TITLE
No 'Other' option for application type. 

### ISSUE THREAD

**Issue by henryw4k** [levz0r/gmail-tester#40]
1. 
![Screen Shot 2020-08-17 at 5 43 31 PM](https://user-images.githubusercontent.com/3743891/90457759-54842100-e0b1-11ea-928d-806fc8a06945.png)
Follow the instructions to Create a client ID and client secret. Make sure to select Other for the application type.

What are you guys selecting for application type?

**Comment by anas-qa** [comment]
@henryw4k you can generate via Web application

However, once you get the json, change it to installed and it will work.

So, in `credentials.json` you shall end up with something similar to
```json
{
  "installed": {
    "client_id": "YOUR_CLIENT_ID",
    "project_id": "PROJECT_ID",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "CLIENT_SECRET",
    "redirect_uris": ["urn:ietf:wg:oauth:2.0:oob", "http://localhost"]
  }
}
```


As the author mentioned, make sure that `credentials.json` and `gmail_token.json` AS ADDED TO `.gitignore`

**Comment by raheel0452** [comment]
Those who might see this in future, selecting `Web Application` will block at next steps. Rather please use `Desktop app`. This will create credentails.json similar to one in readme.

![image](https://user-images.githubusercontent.com/3996649/97981032-faeae300-1dd1-11eb-9bc2-b547244c2bc8.png)
