### ISSUE TITLE
Issue when selecting "Web application" as Type

### ISSUE THREAD

**Issue by cooleiwhistles** [levz0r/gmail-tester#42]
Per documentation Step 1, 

> Follow the instructions to Create a client ID and client secret. Make sure to select Other for the application type.

But I do not see "Other" as an option. I tried as "Web application" instead per https://github.com/levz0r/gmail-tester/issues/40 solution, and changed my json file to contain `installed`, but still got the following error when running setup command:

```
[gmail] Error: TypeError: Cannot read property '0' of undefined
    at Object.authorize 
```

**Comment by leonzalion** [comment]
I guess for those who come across this is the future, this is when `redirect_uris` isn't defined in your client_secret.json

**Comment by raheel0452** [comment]
This can also be fixed by selecting `Desktop app`. This will create credentials.json similar to one in readme and will allow to proceed further.

![image](https://user-images.githubusercontent.com/3996649/97981032-faeae300-1dd1-11eb-9bc2-b547244c2bc8.png)
