### ISSUE TITLE
No Refresh Token is Set

### ISSUE THREAD

**Issue by amerryma** [levz0r/gmail-tester#45]
Hi, I'm currently running into an issue with my tokens using this library. This may in fact be a limitation but just wanted to confirm that I'm not doing anything unexpected here.

When I generate a token (gmail-token.json) it is only good for one hour. Is this expected? I was assuming it would use a refresh token to make requests beyond that time limit. Right now when I hit the hour limit it will return:

```
[gmail] Checking for message from '_', to: _, contains '_' in subject...
The API returned an error: Error: No refresh token is set.
Error when getting recent emails: Error: No refresh token is set.
[gmail] Error: Error: No refresh token is set.
```

Any thoughts? 

Thanks in advance.

**Comment by FredrikRosenqvist** [comment]
Would also like an answer to this, can't really be used in testing if we have to refresh the token manually every hour.

**Comment by amerryma** [comment]
Sure

**Comment by amerryma** [comment]
```
{
  "installed": {
    "client_id": "-.apps.googleusercontent.com",
    "project_id": "-",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "-",
    "redirect_uris": [
      "-"
    ]
  }
}
```

**Comment by levz0r** [comment]
Thank you @amerryma 
Now I can see that "refresh_token" is missing in `gmail-token.json` for some reason 😒
Can you try the init process once again and report if it helped?

**Comment by amerryma** [comment]
Just did it again. Regenerating the token from scratch does not end up adding a `refresh_token` key.

**Comment by levz0r** [comment]
Very strange. I just regenerated my token again, and `refresh_token` is there.
Have you chosen _Desktop app_ when created OAuth Client ID?

**Comment by amerryma** [comment]
Wow, that was it. I think my oauth token was created a while back... looks like the instructions were updated since then, so looks like it's working now after making that change. Thanks!

**Comment by levz0r** [comment]
Great!
