### ISSUE TITLE
Usage in CI environment

### ISSUE THREAD

**Issue by mojilla** [levz0r/gmail-tester#46]
Hi,
A bunch of thanks for this great repo.
I was able to move forward with instruction and inbox reading works perfectly in the local machine

As mentioned in documents we shouldn't push credentials JSON files into the git repository. so, I'm wondering how we should set up the package in the CI environment? is there any advice?

Thanks.

**Comment by levz0r** [comment]
Hello,

One way is to place the credential files in a protected place and reference them in the get_messages/check_inbox task. The paths can be stored in environment variables as well...
