### ISSUE TITLE
:new request: Delete messages function required

### ISSUE THREAD

**Issue by kartikmuchandi** [levz0r/gmail-tester#48]
Sorry for posting this in Issues, however, i am a noob and trying to understand how to use GitHub for now!
Gmail tester is a great addition to my cypress test suites. However, I was looking for a function to delete messages form inbox. 
Any plans to build this in future releases?

**Comment by levz0r** [comment]
Hi,
There are no plans for this feature. However, you can fork this repository and at whatever functionality you need.
More info can be found here: https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo
