### ISSUE TITLE
It generates token with life duration = 1 hour

### ISSUE THREAD

**Issue by kay4444** [levz0r/gmail-tester#50]
I've created "Credentials.json" file as per instructions.
Then I am running the command to generate Token:
`node ..\..\node_modules\gmail-tester\init.js .\credentials.json gmail_token.json test@gmail.com`
It successfully creates Token, **BUT it's life time is just 1 hour**.

```
{
  "access_token": "ya29.a0AfH6SMDwy2 ... xMze5YfDMru-CYaM",
  "refresh_token": "1//09boFIYyEL0w3Cg ... UKq7eNZHeSKxIv3MyZqI",
  "scope": "https://www.googleapis.com/auth/gmail.readonly",
  "token_type": "Bearer",
  "expiry_date": 1610372897000
}
```

**_How extend token life time (to at least half of the year)?_**

**Comment by levz0r** [comment]
According to [this](https://github.com/google/google-api-javascript-client/blob/5c310e0602d46b3796c171fb57e9db15d00c19b6/docs/faq.md#how-do-i-refresh-the-auth-token-and-how-often-should-i-do-it), it looks like the access token is now expiring after one hour. I'll expose a function to refresh the access token in the coming days.

Thank you for bringing this to my attention.

**Comment by kay4444** [comment]
@levz0r 
Are there any updates?

**Comment by levz0r** [comment]
Yes. I've just pushed a function `refresh_access_token(credentials_json, token_path)` to feature/refresh_token branch. Please check it out.
When you call the function, it will refresh the access token and save it back to token.json. Later this function might become part of `get_messages` function.
Let me know if it helps.

**Comment by kay4444** [comment]
@levz0r 
Could you please clarify how can I call this function?
I use the following command to generate token:
node ..\..\node_modules\gmail-tester\init.js .\credentials.json gmail_token.json test@gmail.com
Should I update this command somehow to force your fix to work (generate token with correct duration time)?

**Comment by levz0r** [comment]
After creating token.json with init function you get an access token which is valid for one hour. You should basically check how old is your token (there is a field in token.json which has timestamp) and if it is older than one hour, you should call the refresh_access_token function which will extend it's validity by one more hour.

**Comment by C-E-Rios** [comment]
Hey @levz0r , thanks for the branch. Will you be merging this any time soon?

**Comment by levz0r** [comment]
Can you guys please confirm the new method solves the issue?

**Comment by NikolaLohinski** [comment]
Hi @levz0r and thanks for the tool, it works perfectly fine with Cypress

The refresh_token seems to be working for me. I would love to see that in `master`
