### ISSUE TITLE
Getting 403 access_denied when running init.js

### ISSUE THREAD

**Issue by shorsher** [levz0r/gmail-tester#53]
I'm sure this is an error with what I am doing, but I seem to be following the instructions exactly. 
My steps:
1. Create credentials.json with google account `myaccount@gmail.com`
2. Download credentials and place into `cypress/plugins`
3. Run command: `node ../node_modules/gmail-tester/init.js ./credentials.json gmail_token.json myaccount@gmail.com`

After clicking on the link and trying to sign into `myaccount@gmail.com`, I get the following error:

```
The developer hasn’t given you access to this app. It’s currently being tested and it hasn’t been verified by Google. If you think you should have access, contact the developer
```

Have you ran into this before?

**Comment by shorsher** [comment]
needed to grant specific access to my user, closing.

**Comment by Hganavak** [comment]
Could you provide some more helpful information on how you resolved this @shorsher?

**Comment by dkoudrinhc** [comment]
It's as he said, in the google console you need to add at least one 'user' to your project, then it works. Funnily this was not in the documentation at all.
