### ISSUE TITLE
Token expire after 7 days

### ISSUE THREAD

**Issue by muhammadmubeen12345** [levz0r/gmail-tester#56]
How to automatically update the token in gmail API.

**Comment by damasofc** [comment]
I'm with the same issue, of course I know about the function refres-token that @levz0r created, but even using that function returns me an error "invalid_grant", if you could give us a complete example on how to use refresh-token would be great @levz0r 

thank you in advanced

**Comment by LordA98** [comment]
Yeah I have the same problem.  Not sure how long it's lasting exactly but the refresh_access_token function is not working.

**Comment by LordA98** [comment]
@muhammadmubeen12345 @damasofc @pakhilov 

Did any of you find a solution / workaround in the end?

**Comment by muhammadmubeen12345** [comment]
@LordA98  I have not found any solution about update of token. Every Monday I update the token manually...

**Comment by riccardogiorato** [comment]
Hey @LordA98 and @muhammadmubeen12345 have you both tried ["refresh_access_token"](https://github.com/levz0r/gmail-tester#refresh_access_tokencredentials_json-token_path)?

I just added to my cypress project easily with this file: [refreshGmailToken.js](https://github.com/riccardogiorato/cypress-for-everything/blob/main/cypress/plugins/refreshGmailToken.js).

![image](https://user-images.githubusercontent.com/4527364/131245429-845d36a9-86d5-4417-b7d8-a3cc851fc4da.png)

I then call this script on each CI run uploading the new token to S3 here: [github workflow](https://github.com/riccardogiorato/cypress-for-everything/blob/main/.github/workflows/main.yml#L63-L67)!

![image](https://user-images.githubusercontent.com/4527364/131245447-ca67dcc5-9b16-40d7-9315-c892f6af37aa.png)

This will be downloaded by the following runs!

**Comment by the-bmc-dev** [comment]
> Hey @LordA98 and @muhammadmubeen12345 have you both tried ["refresh_access_token"](https://github.com/levz0r/gmail-tester#refresh_access_tokencredentials_json-token_path)?
> 
> I just added to my cypress project easily with this file: [refreshGmailToken.ts](https://github.com/riccardogiorato/cypress-for-everything/blob/main/cypress/plugins/refreshGmailToken.ts).
> 
> ![image](https://user-images.githubusercontent.com/4527364/131245429-845d36a9-86d5-4417-b7d8-a3cc851fc4da.png)
> 
> I then call this script on each CI run uploading the new token to S3 here: [github workflow](https://github.com/riccardogiorato/cypress-for-everything/blob/main/.github/workflows/main.yml#L63-L67)!
> 
> ![image](https://user-images.githubusercontent.com/4527364/131245447-ca67dcc5-9b16-40d7-9315-c892f6af37aa.png)
> 
> This will be downloaded by the following runs!
> 
> I hope I was able to help you and if you need more help just let me know! If I helped you can star my repository here where I test all sort of stuff with cypress, gmail and more: https://github.com/riccardogiorato/cypress-for-everything

Yes, even after using the refresh_access_token function, the 'invalid_grant' error will eventually show up.

**Comment by levz0r** [comment]
@the-bmc-dev can it be because you are scanning the inbox too frequently of using broad filters?

**Comment by the-bmc-dev** [comment]
@levz0r I did not think about that, are there such restrictions on Gmail API?

**Comment by omersomuncu** [comment]
Hi,
I created this in plugins/index.js
`  on("task", {
    "gmail:refresh_access_token": async () => {
      const token = await gmail_tester.refresh_access_token(
        path.resolve(__dirname, "credentials.json"),
        path.resolve(__dirname, "token.json")
      );
      console.log("Refreshed the gmail token!");
      return token;
    },
  });`

and I call it like this in my test:
`cy.task("gmail:refresh_access_token");`

I am getting this error:
`cy.task('gmail:refresh_access_token') failed with the following error:

> No refresh token is set.`

Any idea where do I make mistake?

**Comment by dkoudrinhc** [comment]
> Hi, I created this in plugins/index.js ` on("task", { "gmail:refresh_access_token": async () => { const token = await gmail_tester.refresh_access_token( path.resolve(__dirname, "credentials.json"), path.resolve(__dirname, "token.json") ); console.log("Refreshed the gmail token!"); return token; }, });`
> 
> ![Screenshot 2021-12-21 at 12 00 51](https://user-images.githubusercontent.com/90185775/146919462-36e8cb8f-8e37-4df9-9b83-4ef03d6301fb.png)
> 
> and I call it like this in my test: `cy.task("gmail:refresh_access_token");`
> 
> I am getting this error:
> 
> ```
> `cy.task('gmail:refresh_access_token') failed with the following error:
> 
> > No refresh token is set.`
> ```
> 
> Any idea where do I make mistake?

Thanks for the code example. I too would love to hear how others are using it, otherwise without a fully working refresh token they expire every two days so the whole plugin becomes not very useful.

**Comment by omersomuncu** [comment]
Hey folks,

I find the solution.

**First of all, do not forget to add "refresh_token":"Your token" to your token.json!!!**
After that index.js:
<img width="669" alt="Screenshot 2021-12-28 at 13 04 04" src="https://user-images.githubusercontent.com/90185775/147564518-f6b2024f-27d5-4643-b27c-c598a0ea4aed.png">

It's ready to test: cy.task("gmail:refresh_access_token", {});

Have fun!

**Comment by dkoudrinhc** [comment]
> Hey folks,
> 
> I find the solution.
> 
> **First of all, do not forget to add "refresh_token":"Your token" to your token.json!!!** After that index.js: <img alt="Screenshot 2021-12-28 at 13 04 04" width="669" src="https://user-images.githubusercontent.com/90185775/147564518-f6b2024f-27d5-4643-b27c-c598a0ea4aed.png">
> 
> It's ready to test: cy.task("gmail:refresh_access_token", {});
> 
> Have fun!

Unfortunately this didn't seem to help at all, it just says 'invalid_grant' when running the refresh_token task now. e.g. CypressError: `cy.task('gmail:refresh_access_token')` failed with the following error:
> invalid_grant

**Comment by josego1984** [comment]
Hi,
I'm using the refress_access_token function but it requires to open a url and the copy again the code. Is there any way to avoid this?

**Comment by digitalgopnik** [comment]
> Hey folks,
> 
> I find the solution.
> 
> **First of all, do not forget to add "refresh_token":"Your token" to your token.json!!!** After that index.js: <img alt="Screenshot 2021-12-28 at 13 04 04" width="669" src="https://user-images.githubusercontent.com/90185775/147564518-f6b2024f-27d5-4643-b27c-c598a0ea4aed.png">
> 
> It's ready to test: cy.task("gmail:refresh_access_token", {});
> 
> Have fun!

@omersomuncu Check [this issue](https://github.com/levz0r/gmail-tester/issues/45). The key `refresh_token` should be set, check your applicationtype-setting for the client -> should be *Desktop app*

**Comment by taninnazar** [comment]
@levz0r could you please help to resolve this issue?

**Comment by Revadike** [comment]
would be nice to have this done automatically
also, the above solutions only work if you save token.json file to disk

**Comment by mariamaslam** [comment]
Hi @omersomuncu im trying to solution i don't have a CI/CD pipeline. I am just executing the test from terminal. How can i automatically refresh the token?
Please can anyone support ?
@Revadike @taninnazar @levz0r

**Comment by taninnazar** [comment]
@mariamaslam there is nothing to do with a code. To have a stable token you need to change the Publishing status of your Google app from "In testing" to "In production". You can do it here - https://console.cloud.google.com/apis/credentials/consent

**Comment by mariamaslam** [comment]
Hi @taninnazar thank you quick response, so once changed to "in production" the token will not expire right?

**Comment by mariamaslam** [comment]
Amazinggg @taninnazar do i just need to change the permission n that would be it or do i need to re- generate the token with gmail-tester?

**Comment by harishdhande01** [comment]
aany solution @mariamaslam

**Comment by piozaj** [comment]
Solution:
You need to change Publishing status of your app in Google Cloud Console from Testing to In Production.
<img width="961" alt="Screenshot 2024-10-30 at 5 04 13 PM" src="https://github.com/user-attachments/assets/77d4dce4-e5cc-4a7b-93b7-a0f4a65cdddf">

More info why it expires after 7 days:
https://support.google.com/cloud/answer/10311615?authuser=1&fbclid=IwY2xjawGPPJNleHRuA2FlbQIxMAABHftjUT5ZbPwxUNH-hUZbEew-SvlOVO7tX5T-xahO988-czCywGIvcdhu0Q_aem_7MdyaMGfc9nCgkQ3SyCu9g#publishing-status&zippy=%2Ctesting
