### ISSUE TITLE
GaxiosError: Mail service not enabled

### ISSUE THREAD

**Issue by LordA98** [levz0r/gmail-tester#57]
Hi,

I'm fairly confident that this is something that I'm doing wrong (rather than an issue with the package) but I haven't been able to fix it.

I get a 'Mail service not enabled' error when running this command:

`node ../../../node_modules/gmail-tester/init.js ./credentials.json gmail_token.json test@gmail.com`

This is part of the JSON output:

```
errors: [
    {
      message: 'Mail service not enabled',
      domain: 'global',
      reason: 'failedPrecondition'
    }
]
```

The JSON output also mentions the gmail.readonly scope. So, I thought I needed to enable that OAuth consent screen (which I have done) but that has not fixed it.

Does it matter what Google account has registered the OAuth consent screen and been added as a user, etc?

My Google account that hosts the project is just my personal email (not my company domain).  I also added my personal email as a test user so that I could click the link and follow the process through to get a token.

Is that right?  Or should I have created a Gmail account for my 'no-reply@domain.com' email address and added that?

**Comment by LordA98** [comment]
Some places suggest that this is caused because 'isMailboxSetup' is false?   I haven't been able to confirm this yet.

My personal account (that hosts the project and gets the token) is a hotmail account so might not have this enabled?

**Comment by levz0r** [comment]
This library works only on **gmail** accounts where you authorized it. You are receiving the error most likely because the library was not approved on test@gmail.com.

**Comment by LordA98** [comment]
So, does my OAuth project need to be under a Gmail account?  Or do I need to provide access to a Gmail account?  Or am I still not understanding?

**Comment by levz0r** [comment]
You should use test@gmail.com when logging in to https://console.cloud.google.com/apis

**Comment by LordA98** [comment]
![image](https://user-images.githubusercontent.com/25960574/115627593-35e8c080-a2f7-11eb-9116-8a0727dfa631.png)

**Comment by LordA98** [comment]
I solved this issue by creating a new Gmail specifically for testing (rather than using my personal @hotmail) account.  The account that hosts the project containing the Google Project / OAuth Client ID / Consent Screen needed to be @gmail.

**Comment by sanket3103** [comment]
I am getting this issue intermittently....For some users Got this error and running it again getting response. That is strange for me.It will be helpful if anyone can explain this issue.
I am getting error when calling 
profile = service.users().getProfile(userId='me').execute() api 

In my understanding there are 2 issues here
1.) when account is not gmail account 
2.) intermittent issue which I am not able to understand (reason being if account is not gmail account it wont work 2nd time as well)
