### ISSUE TITLE
To delete a mail  

### ISSUE THREAD

**Issue by rudyhadoux** [levz0r/gmail-tester#58]
Hi,

Do you plan to add function to delete an email ?
It could be great.
Thanks.

**Comment by levz0r** [comment]
Hi @rudyhadoux, thanks for the feature request.
gmail-tester is meant to check gmail inboxes for emails, not to manage the inbox. Please feel free to fork the repository and implement it :)

**Comment by rudyhadoux** [comment]
For Cypress tests, it is good to do a CRUD with emails.
