### ISSUE TITLE
"gmail:check-inbox" timing out after 60 seconds despite "max_wait_time_sec" being set to 180

### ISSUE THREAD

**Issue by alexcampbell86** [levz0r/gmail-tester#59]
I am using `gmail:check-inbox` with the following task definition:

```
    on('task', {
        'gmail:check-inbox': async args => {
            return await gmail_tester.check_inbox(
                path.resolve('src/support/credentials/google', 'googleCredentials.json'),
                path.resolve('src/support/credentials/google', 'googleToken.json'),
                args.options
            );
        },
    });
```

And am calling with these args:

```
   cy.task("gmail:check-inbox", {
       options: {
           to: user,
           from: sender,
           include_body: true,
           wait_time_sec: 5,
           max_wait_time_sec: 180
       }
   }
```

I am seeing some intermittent failures with the following logged:

`CypressError: `cy.task('gmail:check-inbox')` timed out after waiting `60000ms`.`

I would expect the timeout to occur after 180000ms , not 60000ms. Am I missing something?

**Comment by CFacu** [comment]
Hi, having the same issue here, did you find any solution for this?

<img width="703" alt="Screen Shot 2021-06-02 at 17 01 51" src="https://user-images.githubusercontent.com/40407870/120545353-ecdf5e00-c3c4-11eb-8488-3fcafd01632a.png">
<img width="541" alt="Screen Shot 2021-06-02 at 17 02 59" src="https://user-images.githubusercontent.com/40407870/120545362-ee108b00-c3c4-11eb-9c3c-c7ca79b4908f.png">

**Comment by alexcampbell86** [comment]
HI @CFacu I did not find a solution but was able to pinpoint the failure on actual email delivery issues (e.g., waiting longer would not have resolved it).

**Comment by levz0r** [comment]
Hi, this issue is not related to gmail-tester. Please see https://docs.cypress.io/guides/references/configuration#Timeouts
