### ISSUE TITLE
After/before options not working

### ISSUE THREAD

**Issue by peykens** [levz0r/gmail-tester#6]
When I try to use the before or after options in the get_messages, I get an exception:
 [gmail] Error: TypeError: after.getFullYear is not a function

I pass a "new Date" as value. But it seems that it's passed s string iso Date.

When I patch the module to parse it back to a Date() in the init-query, it seems to work.

function _init_query(options) {
  const { before, after } = options;
  let query = "";
  if (before) {
    let beforeDate = new Date(before);    
    query += `before:${beforeDate.getFullYear()}/${beforeDate.getMonth()}/${beforeDate.getDate()} `;
  }
  if (after) {
    let afterDate = new Date(after);    
    query += `after:${afterDate.getFullYear()}/${afterDate.getMonth()}/${afterDate.getDate()} `;
  }
  query = query.trim();
  return query;
}

**Comment by levz0r** [comment]
Can you show your code which calls `get_messages`?

**Comment by peykens** [comment]
let timeStamp= new Date();

cy.task("mail:get-messages", {
            options: {
              include_body: false,
              after: timeStamp
            }

**Comment by levz0r** [comment]
Thanks, I could reproduce the bug. It seems that cypress converts the date to string when passing the args to the task.

**Comment by levz0r** [comment]
Here is the issue in their repo: https://github.com/cypress-io/cypress/issues/4980

Let's see how it develops there...

**Comment by ayyazzafar** [comment]
@levz0r First of all Thanks for such a great plugin. I used it and it worked really well.
But I am also facing same issue. I am not able to use before and after. 
Is there any update regarding this?

**Comment by levz0r** [comment]
Hello @ayyazzafar and welcome :)

I've just provided some details for cypress maintainers: https://github.com/cypress-io/cypress/issues/4980#issuecomment-531192624

I hope will

**Comment by levz0r** [comment]
Fixed some 7 months ago :)

Closing.
