### ISSUE TITLE
gmail:check from within a cypress test timesout Error [ERR_IPC_CHANNEL_CLOSED] [ERR_IPC_CHANNEL_CLOSED]: Channel closed

### ISSUE THREAD

**Issue by timrabbetts** [levz0r/gmail-tester#66]
Using this within cypress trying to check an email, eventually want to extract and click the verify link.  When it hits the check mail step it just falls over, error not overly helpful, wonder if you can advise what I might have got wrong.  I followed this post: https://levz0r.medium.com/how-to-poll-a-gmail-inbox-in-cypress-io-a4286cfdb888

Oh, in that post the test says "email not found" but I think its suppose to say email found??  Anyways....

Here is my index.js file

```js
const path = require("path");
const gmail = require("gmail-tester");

module.exports = (on, config) => {

  on("task", {
    "gmail:check": async args => {
      const { from, to, subject } = args;
      const email = await gmail.check_inbox(
        path.resolve(__dirname, "credentials.json"), // credentials.json is inside plugins/ directory.
        path.resolve(__dirname, "gmail_token.json"), // gmail_token.json is inside plugins/ directory.
        subject,
        from,
        to,
        30,                                          // Poll interval (in seconds)
        60                                           // Maximum poll interval (in seconds). If reached, return null, indicating the completion of the task().
      );
      console.log('gmail check is working');
      return email;
    }
  });

};
```

here is my test.js file:

```js
it('link is no longer valid, we can request and new one and the new link works', () => {

  cy.visit('/urlforresetform');

  // Check we get the email and its content is correct.
  const test_id = new Date().getTime();
  const incoming_mailbox = `myemail+${test_id}@gmail.com`;
  const password = 'somepassword';

  cy.get("#edit-name").type(incoming_mailbox);
  cy.get("#edit-submit").click();

  cy
    .task("gmail:check", {
      from: "mysitesemailaddress",
      to: incoming_mailbox,
      subject: "emailtitle"
    })
    .then(email => {

      console.log('we have an email??');
      assert.isNotNull(email, `Email was found!`);
    });

})
```

**Comment by timrabbetts** [comment]
I've defo setup Gmail account correct, and the creds token etc are correct and generated, I can see the email in my gmail account.  Its just not querying the account for some reason.

**Comment by timrabbetts** [comment]
package.json

<pre>
{
  "devDependencies": {
    "cypress": "^7.6.0",
    "cypress-file-upload": "^5.0.8",
    "gmail-tester": "^1.3.2"
  },
  "dependencies": {}
}
</pre>

**Comment by levz0r** [comment]
Hi, can you please upgrade to v1.3.3 and give it another try?

**Comment by timrabbetts** [comment]
Was already on latest version.  Got it working, the examples are a bit out of date.  I wasnt passing the data correctgly to start with.

<pre>

Cypress.Commands.add('signup', () => {
  cy.visit('/userregpath');

  const test_id = new Date().getTime();
  const incoming_mailbox = 'cyptst007+' + test_id + '@gmail.com';

  cy.get("#email").type(incoming_mailbox);
  cy.get("#submit").click();

  // Check we get the email and its content is correct.
  cy
    .task("gmail:check", {
      from: "My Site <postmaster@mysite.com>",
      to: incoming_mailbox,
      subject: "Please verify your account at bla"
    })
    .then(email => {
      // Extract the verify link url from the email.
      const verify_url = /<a id="my-ver-link".*?href=\"([^\"]*)\">/.exec(email[0].body.html)[1];

      // Use an alias to store the value, which we can wait for in next step.
      cy.wrap(verify_url).as('verifyUrl');

      // Confirm we got an email.
      assert.isNotNull(email, `Email was found!`);
    });

  // Visit the verify url once we get it from the email, confirm we get the correct form.
  cy.get('@verifyUrl').then((verifyUrl) => {
    cy.visit(verifyUrl);    
  })
})

</pre>

<pre>
const path = require("path");
const gmail = require("gmail-tester");

module.exports = (on, config) => {

  on("task", {
    async "gmail:check" (args) {
      const {from, to, subject} = args;

      const options = {
        subject: subject,
        from: '*',
        to: to,
        wait_time_sec: 30,
        max_wait_time_sec: 60,
        include_body: true
      }

      const email = await gmail.check_inbox(
         path.resolve(__dirname, "credentials.json"),
         path.resolve(__dirname, "gmail_token.json"),
         options,
      );

      return email;

    },
  });

};
</pre>

**Comment by timrabbetts** [comment]
const verify_url = /<a id="verify-account".*?href=\"([^\"]*)\">/.exec(email[0].body.html)[1];

**Comment by danlynkew** [comment]
I'm experiencing and struggling with this error. @timrabbetts Can you tell me how you solved this problem?

**Comment by timrabbetts** [comment]
The main issue is the check_inbox was getting called with 7 variables, what it actually needs is 3 variables, the 2 json files and then an options variable, that was the main problem solver for me, the code above works so give it a try.  Hope this helps.

**Comment by levz0r** [comment]
I am glad you solved this. Can we close the issue?
