### ISSUE TITLE
Cant select label on gmail 

### ISSUE THREAD

**Issue by ThrowMasta** [levz0r/gmail-tester#68]
cy.task("gmail:get-messages", {
          options: {
              label                   : "SPAM",
              subject                 : subject, // We are looking for 'Activate Your Account' in the subject of the message.
              from                    : from, // We are looking for a sender header which is 'no-reply@domain.com'.
              to                      : to, // Which inbox to poll. credentials.json should contain the credentials to it.
              wait_time_sec           : 10, // Poll interval (in seconds).
              max_wait_time_sec       : 30, // Maximum poll time (in seconds), after which we'll giveup.
              include_body: true
          }
      })

as you can see i alr set label on "SPAM" but
whenever i set label to others label it will only ready the INBOX only. may i know whats wrong with this? can someone do example for me

**Comment by levz0r** [comment]
Hi,
Remove the `options` object from the 2nd parameter:
```
 cy.task("gmail:get-messages", {
          label                   : "SPAM",
          subject                 : subject, // We are looking for 'Activate Your Account' in the subject of the message.
          from                    : from, // We are looking for a sender header which is 'no-reply@domain.com'.
          to                      : to, // Which inbox to poll. credentials.json should contain the credentials to it.
          wait_time_sec           : 10, // Poll interval (in seconds).
          max_wait_time_sec       : 30, // Maximum poll time (in seconds), after which we'll giveup.
          include_body: true
  })
```

**Comment by levz0r** [comment]
Hi, your code looks fine. I just verified it works on my end. Why do you think it searches in INBOX?

**Comment by ThrowMasta** [comment]
> Hi, your code looks fine. I just verified it works on my end. Why do you think it searches in INBOX?

when i console still pull the inbox not the spam folder dont know whats wrong with this or do i wrong give the params?

**Comment by levz0r** [comment]
Have you managed to resolve the issue @ThrowMasta?

**Comment by levz0r** [comment]
@ThrowMasta I am closing the issue, but if the problem still exists feel free to reopen.
