### ISSUE TITLE
Get email body with the check_inbox function

### ISSUE THREAD

**Issue by templth** [levz0r/gmail-tester#7]
Hello,

Thanks very much for this very useful lib!

I wonder if it's possible to get the email content when using the `check_inbox` function. I had a look at the code and this doesn't seem to be supported.

Thanks for your help!
Thierry

**Comment by templth** [comment]
Here is the corresponding PR: https://github.com/levz0r/gmail-tester/pull/8

**Comment by levz0r** [comment]
Hi Thierry,

Thank you for your feedback :)

Basically, I'm thinking to make `check_inbox` obsolete in the further versions because there is no real need in it anymore.

Maybe I'm wrong though... What's you use case?

**Comment by templth** [comment]
Hey Lev,

You're welcome ;-)

My use case is to test the complete onboarding chain of an application:

* Register with an email
* Receive an email with a link in it to complete the registration process
* Go to this link
* Fill the remaining hints
* Finalize registration

Do you think it possible to achieve this without using the `check_inbox` function? If so, what can I use instead?

Thanks very much!
Thierry

**Comment by levz0r** [comment]
Absolutely possible! 

You can read how we test a similar process here: https://medium.com/p/how-to-poll-a-gmail-inbox-in-cypress-io-a4286cfdb888

Feel free to open a ticket if appropriate.

**Comment by levz0r** [comment]
P.S

Although in the post we are using `check_inbox`, we do not do assertions on the email body. If we would need to, we would use `get_messages`...

**Comment by dsmurrell** [comment]
Hey @levz0r, I'm trying this out now and I believe that check_inbox has some useful functionality that get_messages is missing. That is, it waits for a while until it grabs the exact email you're looking for. I'm also writing some tests which rely on sending a registration email off and doing something with the body when it arrives in the gmail inbox, and I'm finding that if I use get_messages alone, then it gets them too early - before the email I want has arrived and my tests fail.

I can use check_inbox and then run get_messages, which works, and which I am resorting to now, but having the body come back as part of check_inbox for a single email sure would be handy. It would be far less code in the testing framework and also 1 let call to _get_recent_email.

Might it be worth accepting PR: https://github.com/levz0r/gmail-tester/pull/8 as submitted by @templth ?
