### ISSUE TITLE
Function returns undefined for emails contains attachments

### ISSUE THREAD

**Issue by DanielNovicky** [levz0r/gmail-tester#75]
Hello guys, I have an issue if I want to read email content <include_body: true>  and my email contains attachments (In my case .html file) the function returns me a undefined value.
------------------------------
CypressError: `cy.task('gmail:get-messages')` failed with the following 
he task 'gmail:get-messages' returned undefined. You must return a value, null, or a promise that resolves to a value or null to indicate that the task was handled.
...
Fix this in your plugins file here:
C:\Users\...\Tests\cypress\plugins\index.js

**Comment by JSantosToptal** [comment]
Same issue here!
