### ISSUE TITLE
does Google OAuth interactions compliance changes affect this repo

### ISSUE THREAD

**Issue by HananArgov** [levz0r/gmail-tester#93]
according to the following blog entry, there are going to be compliance changes for applications:
https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html

does this affect anything here?

**Comment by levz0r** [comment]
Hello,
The library was affected by this change. A version supporting the updated flows was published today.

**Comment by dsaintpierre** [comment]
@levz0r a lot of the README instructions are out of date for this still, most notably regarding authorization.
